books/urls.py
from django.urls import path, include
from . import views

app_name = 'books'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:author_id>/', views.detail, name='detail'),
    path('<int:author_id>/<int:book_id>/', views.description, name='description'),
    path('all_books/', views.all_books, name='all_books'),
    path('search/', views.search, name='search'),
    path('<int:author_id>/<int:book_id>/add_comment/', views.add_comment, name='add_comment'),
    path('add_author/', views.add_author, name='add_author'),
    path('add_books/', views.add_books, name='add_books'),
]

library/library/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path(r'', include('books.urls')),
    path('admin/', admin.site.urls),
    path('books/', include('books.urls')),
    path('loginsys/', include('loginsys.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path(r'', include('books.urls')),
    path('admin/', admin.site.urls),
    path('books/', include('books.urls')),
    path('loginsys/', include('loginsys.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

loginsys/urls.py
from django.urls import path, include
from . import views

app_name = 'loginsys'
urlpatterns = [
    path('login_user/', views.login_user, name='login_user'),
    path('logout_user/', views.logout_user, name='logout_user'),
    path('register/', views.register, name='register'),
]

library/loginsys/models.py
from django.db import models

# Create your models here.

loginsys/models.py
from django.db import models

# Create your models here.

library/loginsys/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class' : 'col-md-12 form-control'}))
    class Meta:
        model = User
        fields = ['username', 'email', 'password']
        widgets = {
            'username' : forms.TextInput(attrs={'class' : 'col-md-12 form-control'}),
            'email' : forms.TextInput(attrs={'class' : 'col-md-12 form-control'})
        }

loginsys/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class' : 'col-md-12 form-control'}))
    class Meta:
        model = User
        fields = ['username', 'email', 'password']
        widgets = {
            'username' : forms.TextInput(attrs={'class' : 'col-md-12 form-control'}),
            'email' : forms.TextInput(attrs={'class' : 'col-md-12 form-control'})
        }

library/loginsys/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from .forms import UserForm

def login_user(request):
	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		if user is not None:
			if user.is_active:
				login(request, user)
				return redirect('books:index') # переход на страницу, после авторизации

			return render(request, 'loginsys/login_user.html', {
				'error_message': 'Ваш аккаунт был деактивирован'
				})
		else:
			return render(request, 'loginsys/login.html', {
				'error_message': 'Неправильный логин или пароль. Попробуйте заново'
				})
	return render(request, 'loginsys/login.html')

def logout_user(request):
	logout(request)
	# form = UserForm(request.POST)
	# return render(request, 'loginsys/login.html', {'form': form})
	return redirect('loginsys:login_user')

def register(request):
	form = UserForm(request.POST or None)
	if form.is_valid():
		user = form.save(commit=False)
		username = form.cleaned_data['username']
		password = form.cleaned_data['password']
		email = form.cleaned_data['email']
		user.set_password(password)
		user.save()
		user = authenticate(username=username, password=password)
		if user.is_active:
			login(request, user)
			return redirect('books:index')
		return render(request, 'loginsys/login_user.html', {
				'error_message': 'Ваш аккаунт был деактивирован'
				})
	return render(request, 'loginsys/register.html', {'form': form})

loginsys/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from .forms import UserForm

def login_user(request):
	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		if user is not None:
			if user.is_active:
				login(request, user)
				return redirect('books:index') # переход на страницу, после авторизации

			return render(request, 'loginsys/login_user.html', {
				'error_message': 'Ваш аккаунт был деактивирован'
				})
		else:
			return render(request, 'loginsys/login.html', {
				'error_message': 'Неправильный логин или пароль. Попробуйте заново'
				})
	return render(request, 'loginsys/login.html')

def logout_user(request):
	logout(request)
	# form = UserForm(request.POST)
	# return render(request, 'loginsys/login.html', {'form': form})
	return redirect('loginsys:login_user')

def register(request):
	form = UserForm(request.POST or None)
	if form.is_valid():
		user = form.save(commit=False)
		username = form.cleaned_data['username']
		password = form.cleaned_data['password']
		email = form.cleaned_data['email']
		user.set_password(password)
		user.save()
		user = authenticate(username=username, password=password)
		if user.is_active:
			login(request, user)
			return redirect('books:index')
		return render(request, 'loginsys/login_user.html', {
				'error_message': 'Ваш аккаунт был деактивирован'
				})
	return render(request, 'loginsys/register.html', {'form': form})

loginsys/templates/loginsys/form_template.html
{% for field in form %}
	<div class="form-group">
		<div class=""> <!-- col-sm-offset-21 col-sm-101 -->
			<span class="text-danger small">{{ field.errors }}</span>								
		</div>
		<label class="control-label"><h4>{{ field.label_tag }}<h4></label> <!-- control-label col-sm-2 -->
		<div class="field">{{ field }}</div> <!-- col-sm-10 -->
	</div>
{% endfor %}

loginsys/templates/loginsys/login.html
{% extends 'books/base.html' %}
{% block title %}Login{% endblock %}

{% block body %}
{% if error_message %}
	<p><strong>{{ error_message }}</strong></p>
{% endif %}
<div class="layout-form">
	<div class="form">
		<form action="" method="post">
			{% csrf_token %}
			<label for="id_username">
				Логин:
			</label><br>
			<input id="id_username" maxlength="50" class="form-control" name="username" type="text"><br>
			<label for="id_password">
				Пароль:
			</label><br>
			<input id="id_password" maxlength="50" name="password" class="form-control" type="password"><br>
			<button type="submit" class="btn btn-success">Войти</button>
			<a href="{% url 'loginsys:register' %}">Нет логина? Зарегистрируйтесь</a>
		</form>
	</div>
</div>
{% endblock %}

loginsys/templates/loginsys/register.html
{% extends 'books/base.html' %}
{% block title %}Регистрация{% endblock %}

{% block body %}
<div class="layout-form">
	<div class="form">
		<h3>Регистрация</h3>
		{% if error_message %}
			<p><strong>{{ error_message }}</strong></p>
		{% endif %}
		<form action="" method="post">
			{% csrf_token %}
			{% include 'loginsys/form_template.html' %}
			<button type="submit" class="btn btn-success">Зарегистрироваться</button>
		</form>
	</div>
</div>
{% endblock %}