books/urls.py
from django.urls import path, include
from . import views

app_name = 'books'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:author_id>/', views.detail, name='detail'),
    path('<int:author_id>/<int:book_id>/', views.description, name='description'),
    path('all_books/', views.all_books, name='all_books'),
    path('search/', views.search, name='search'),
    path('<int:author_id>/<int:book_id>/add_comment/', views.add_comment, name='add_comment'),
    path('add_author/', views.add_author, name='add_author'),
    path('add_books/', views.add_books, name='add_books'),
]

library/books/urls.py
from django.urls import path, include
from . import views

app_name = 'books'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:author_id>/', views.detail, name='detail'),
    path('<int:author_id>/<int:book_id>/', views.description, name='description'),
    path('all_books/', views.all_books, name='all_books'),
    path('search/', views.search, name='search'),
    path('<int:author_id>/<int:book_id>/add_comment/', views.add_comment, name='add_comment'),
    path('add_author/', views.add_author, name='add_author'),
    path('add_books/', views.add_books, name='add_books'),
]

library/library/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path(r'', include('books.urls')),
    path('admin/', admin.site.urls),
    path('books/', include('books.urls')),
    path('loginsys/', include('loginsys.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path(r'', include('books.urls')),
    path('admin/', admin.site.urls),
    path('books/', include('books.urls')),
    path('loginsys/', include('loginsys.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

loginsys/urls.py
from django.urls import path, include
from . import views

app_name = 'loginsys'
urlpatterns = [
    path('login_user/', views.login_user, name='login_user'),
    path('logout_user/', views.logout_user, name='logout_user'),
    path('register/', views.register, name='register'),
]

books/models.py
from django.db import models
from django.contrib.auth.models import User


# GENRE_CHOICES = (
# 	('Фантастика'),
# 	('Ужастика'),
# 	('Исторический'))

class Author(models.Model):
    writer = models.CharField(u'Автор', max_length=200)
    verbose_name = (u'Автор')

    def __str__(self):
        return self.writer

class Book(models.Model):
	author = models.ForeignKey(Author, on_delete=models.CASCADE, verbose_name=u'Автор')
	title = models.CharField('Наименование', max_length=250)
	genre = models.CharField('Жанр', max_length=50)
	description = models.TextField('Описание')
	year = models.IntegerField('Год издания')
	cover = models.ImageField('Обложка', upload_to='static/static_dirs/images/', blank=True)

	
	def __str__(self):
		return self.title + ' (' + str(self.year) + ')'

class Comment(models.Model):
	book = models.ForeignKey(Book, on_delete=models.CASCADE)
	comment_text = models.CharField('Текст комментария', max_length=500)
	user_name = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		return self.comment_text

library/books/models.py
from django.db import models
from django.contrib.auth.models import User


# GENRE_CHOICES = (
# 	('Фантастика'),
# 	('Ужастика'),
# 	('Исторический'))

class Author(models.Model):
    writer = models.CharField(u'Автор', max_length=200)
    verbose_name = (u'Автор')

    def __str__(self):
        return self.writer

class Book(models.Model):
	author = models.ForeignKey(Author, on_delete=models.CASCADE, verbose_name=u'Автор')
	title = models.CharField('Наименование', max_length=250)
	genre = models.CharField('Жанр', max_length=50)
	description = models.TextField('Описание')
	year = models.IntegerField('Год издания')
	cover = models.ImageField('Обложка', upload_to='static/static_dirs/images/', blank=True)

	
	def __str__(self):
		return self.title + ' (' + str(self.year) + ')'

class Comment(models.Model):
	book = models.ForeignKey(Book, on_delete=models.CASCADE)
	comment_text = models.CharField('Текст комментария', max_length=500)
	user_name = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		return self.comment_text

books/forms.py
from django.forms import Textarea, ModelChoiceField, ModelForm
from .models import Comment, Author, Book
from django import forms


class CommentForm(ModelForm):
	class Meta:
		model = Comment
		fields = ['comment_text']
		widgets = {
            'comment_text': Textarea(attrs={'cols': 80, 'rows': 5, 'class' : 'form-control'}),
        }

class AddAuthorForm(ModelForm):
	class Meta:
		model = Author
		fields = ['writer']

class BookForm(ModelForm):
    author = ModelChoiceField(queryset=Author.objects.all())
    author = forms.Select(attrs={'class' : 'btn btn-primary dropdown-toggle', 'type' : 'button', 'data-toggle' : 'dropdown'})
    class Meta:
        model = Book
        fields = ['author', 'title', 'description', 'genre', 'year', 'cover']
        widgets = {
		    'author' : forms.Select(attrs={'class' : 'btn btn-primary dropdown-toggle', 'type' : 'button', 'data-toggle' : 'dropdown' }),
			'genre' : forms.TextInput(attrs={'class' : 'col-md-12 form-control'}),
			'year' : forms.TextInput(attrs={'class' : 'col-md-12 form-control'}),
			'cover' : forms.FileInput(attrs={'class' : 'col-md-12 form-control'}),
			'description' : forms.TextInput(attrs={'class' : 'col-md-12 form-control'}),
            'title' : forms.TextInput(attrs={'class' : 'col-md-12 form-control'})
        }

library/books/forms.py
from django.forms import Textarea, ModelChoiceField, ModelForm
from .models import Comment, Author, Book
from django import forms


class CommentForm(ModelForm):
	class Meta:
		model = Comment
		fields = ['comment_text']
		widgets = {
            'comment_text': Textarea(attrs={'cols': 80, 'rows': 5, 'class' : 'form-control'}),
        }

class AddAuthorForm(ModelForm):
	class Meta:
		model = Author
		fields = ['writer']

class BookForm(ModelForm):
    author = ModelChoiceField(queryset=Author.objects.all())
    author = forms.Select(attrs={'class' : 'btn btn-primary dropdown-toggle', 'type' : 'button', 'data-toggle' : 'dropdown'})
    class Meta:
        model = Book
        fields = ['author', 'title', 'description', 'genre', 'year', 'cover']
        widgets = {
		    'author' : forms.Select(attrs={'class' : 'btn btn-primary dropdown-toggle', 'type' : 'button', 'data-toggle' : 'dropdown' }),
			'genre' : forms.TextInput(attrs={'class' : 'col-md-12 form-control'}),
			'year' : forms.TextInput(attrs={'class' : 'col-md-12 form-control'}),
			'cover' : forms.FileInput(attrs={'class' : 'col-md-12 form-control'}),
			'description' : forms.TextInput(attrs={'class' : 'col-md-12 form-control'}),
            'title' : forms.TextInput(attrs={'class' : 'col-md-12 form-control'})
        }

books/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import Author, Book, Comment
from .forms import CommentForm, AddAuthorForm, BookForm

def index(request):
	author = Author.objects.all()
	return render(request, 'books/index.html', {'author': author})

def detail(request, author_id):
	author = get_object_or_404(Author, id=author_id)
	books = Book.objects.filter(author_id=author_id)
	books.author = author
	return render(request, 'books/detail.html', {'books': books, 'author': author})

def description(request, author_id, book_id):
	form = CommentForm
	# author = get_object_or_404(Author, id=author_id)
	book = get_object_or_404(Book, author_id=author_id, id=book_id)
	comments = Comment.objects.filter(book_id=book_id)
	if request.user.is_authenticated:
		return render(request, 'books/description.html', 
			{'book': book, 'form': form, 'comments': comments})
	else:
		error_message = 'Только зарегистрированные могут оставлять комментарии.'
		return render(request, 'books/description.html', 
			{'book': book, 'form': form, 'comments': comments, 'error_message': error_message})

def all_books(request):
	books = Book.objects.all()

	return render(request, 'books/books.html', {'books': books})

def search(request):
	"""
	Поиск книг
	"""
	if 'q' in request.GET:
		q = request.GET['q']
		books = Book.objects.filter(title__icontains=q)
		return render(request, 'books/search.html', 
			{'books': books, 'query': q})
	else:
		return render(request, 'books/search.html', {'error': 'error_message', 'message': 'Unknown request'})

def add_comment(request, author_id, book_id):
	"""
	Добавление комментариев авторизованныи пользователями
	"""
	form = CommentForm(request.POST)
	# author = get_object_or_404(Author, id=author_id)
	book = get_object_or_404(Book, author_id=author_id, id=book_id)
	if request.method == 'POST' and request.user.is_authenticated:
		# Проверка 
		if form.is_valid():
			# Создание
			comment = form.save(commit=False)
			comment.book = book
			# Обновление
			comment.comment_text = request.POST['comment_text']
			username = request.user.get_username()
			comment.user_name = User.objects.get(username=username)
			# Сохранение
			comment.save()
	return HttpResponseRedirect(reverse('books:description', args=(book.author.id, book.id,)))
 

def add_author(request):
	"""
	Добавление авторов только авторизованными пользователями
	"""
	author = Author()
	form = AddAuthorForm
	if not request.user.is_authenticated:
		error_message = 'Только авторизованые пользователи могут добавлять новых авторов.'
		return render(request, 'books/author_form.html', 
			{'form': form, 'error_message': error_message})
	elif request.method == 'POST':
		form = AddAuthorForm(request.POST)
		if form.is_valid():
			author.writer = request.POST['writer']
			author.save()
		return HttpResponseRedirect(reverse('books:index'))
	return render(request, 'books/author_form.html', {'form': form})

def add_books(request):
	"""
	Добавление книги только авторизованными пользователями
	"""
	book = Book()
	form = BookForm
	# Спрятать, если пользователь не авторизован
	if not request.user.is_authenticated:	
		error_message = 'Только авторизованные пользователи могут добавлять книги.'
		return render(request, 'books/addbooks_form.html', 
			{'form': form, 'error_message': error_message})
	elif request.method == 'POST':
		form = BookForm(request.POST)
		writer = request.POST['author']
		author = Author.objects.get(id=int(writer))
		if form.is_valid():
			book.author = author
			book.title = request.POST['title']
			book.genre = request.POST['genre']
			book.year = request.POST['year']
			book.cover = request.POST['cover']
			book.save()
		return HttpResponseRedirect(reverse('books:all_books'))
	return render(request, 'books/addbooks_form.html', {'form': form})

library/books/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import Author, Book, Comment
from .forms import CommentForm, AddAuthorForm, BookForm

def index(request):
	author = Author.objects.all()
	return render(request, 'books/index.html', {'author': author})

def detail(request, author_id):
	author = get_object_or_404(Author, id=author_id)
	books = Book.objects.filter(author_id=author_id)
	books.author = author
	return render(request, 'books/detail.html', {'books': books, 'author': author})

def description(request, author_id, book_id):
	form = CommentForm
	# author = get_object_or_404(Author, id=author_id)
	book = get_object_or_404(Book, author_id=author_id, id=book_id)
	comments = Comment.objects.filter(book_id=book_id)
	if request.user.is_authenticated:
		return render(request, 'books/description.html', 
			{'book': book, 'form': form, 'comments': comments})
	else:
		error_message = 'Только зарегистрированные могут оставлять комментарии.'
		return render(request, 'books/description.html', 
			{'book': book, 'form': form, 'comments': comments, 'error_message': error_message})

def all_books(request):
	books = Book.objects.all()

	return render(request, 'books/books.html', {'books': books})

def search(request):
	"""
	Поиск книг
	"""
	if 'q' in request.GET:
		q = request.GET['q']
		books = Book.objects.filter(title__icontains=q)
		return render(request, 'books/search.html', 
			{'books': books, 'query': q})
	else:
		return render(request, 'books/search.html', {'error': 'error_message', 'message': 'Unknown request'})

def add_comment(request, author_id, book_id):
	"""
	Добавление комментариев авторизованныи пользователями
	"""
	form = CommentForm(request.POST)
	# author = get_object_or_404(Author, id=author_id)
	book = get_object_or_404(Book, author_id=author_id, id=book_id)
	if request.method == 'POST' and request.user.is_authenticated:
		# Проверка 
		if form.is_valid():
			# Создание
			comment = form.save(commit=False)
			comment.book = book
			# Обновление
			comment.comment_text = request.POST['comment_text']
			username = request.user.get_username()
			comment.user_name = User.objects.get(username=username)
			# Сохранение
			comment.save()
	return HttpResponseRedirect(reverse('books:description', args=(book.author.id, book.id,)))
 

def add_author(request):
	"""
	Добавление авторов только авторизованными пользователями
	"""
	author = Author()
	form = AddAuthorForm
	if not request.user.is_authenticated:
		error_message = 'Только авторизованые пользователи могут добавлять новых авторов.'
		return render(request, 'books/author_form.html', 
			{'form': form, 'error_message': error_message})
	elif request.method == 'POST':
		form = AddAuthorForm(request.POST)
		if form.is_valid():
			author.writer = request.POST['writer']
			author.save()
		return HttpResponseRedirect(reverse('books:index'))
	return render(request, 'books/author_form.html', {'form': form})

def add_books(request):
	"""
	Добавление книги только авторизованными пользователями
	"""
	book = Book()
	form = BookForm
	# Спрятать, если пользователь не авторизован
	if not request.user.is_authenticated:	
		error_message = 'Только авторизованные пользователи могут добавлять книги.'
		return render(request, 'books/addbooks_form.html', 
			{'form': form, 'error_message': error_message})
	elif request.method == 'POST':
		form = BookForm(request.POST)
		writer = request.POST['author']
		author = Author.objects.get(id=int(writer))
		if form.is_valid():
			book.author = author
			book.title = request.POST['title']
			book.genre = request.POST['genre']
			book.year = request.POST['year']
			book.cover = request.POST['cover']
			book.save()
		return HttpResponseRedirect(reverse('books:all_books'))
	return render(request, 'books/addbooks_form.html', {'form': form})

books/templates/books/addbooks_form.html
{% extends 'books/base.html' %}
{% block title %}Добавить книгу{% endblock %}

{% block body %}
	<div class="layout-form">
		<div class="form">
			{% if error_message %}
				<p>{{ error_message }}</p>
			{% else %}
				<form action="" method="post">
					{% csrf_token %}
					{% include 'books/form_template.html' %}
					<button type="submit" class="btn btn-success">Добавить книгу</button>
				</form>
			{% endif %}
		</div>
	</div>
{% endblock %}

books/templates/books/author_form.html
{% extends 'books/base.html' %}
{% block title %}Добавить автора{% endblock %}

{% block body %}
	<div class="layout-form">
		<div class="form">
			{% if error_message %}
				<p>{{ error_message }}</p>
			{% else %}
				<form action="" method="post">
					{% csrf_token %}
					{% include 'books/form_template.html'%}
					<br><button type="submit" class="btn btn-success">Добавить автора</button>
				</form>
			{% endif %}
		</div>
	</div>
{% endblock %}

books/templates/books/base.html
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>
	{% load staticfiles %}
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="{% static 'books/css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=PT+Sans" />
	
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body>
	<nav class="navbar navbar-inverse">
		<div class="positioner">
			<div class="conteiner-lfuid">
				<!-- Лого -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="{% url 'books:index' %}">Библиотека</a>
				</div>

				<!-- Навигация -->
				<div class="collapse navbar-collapse" id="topNavBar">
					<ul class="nav navbar-nav">
						<li class="">
							<a href="{% url 'books:index' %}">
								<span class="glyphicon glyphicon-user" aria-hidden="true">
								</span>&nbsp;Авторы
							</a>
						</li>
						<li class="">
							<a href="{% url 'books:all_books' %}">
								<span class="glyphicon glyphicon-book" aria-hidden="true">
								</span>&nbsp;Книги
							</a>
						</li>
					</ul>

					<!-- Поиск -->
					<form class="navbar-form navbar-left" role="search" action="{% url 'books:search' %}" method="get">
						{% csrf_token %}
						<div>
							<input type="text" class="form-control" name="q" value="">
							<button type="submit" class="btn btn-default">Поиск</button>
						</div>
					</form>
					
					<!-- Добавление и выход -->
					<ul class="nav navbar-nav navbar-right">

						<li class="">
							<a href="{% url 'books:add_author' %}">
								<span class="glyphicon glyphicon-plus" aria-hidden="true">
								</span>&nbsp;Добавить автора
							</a>
						</li>
						<li class="">
							<a href="{% url 'books:add_books' %}">
								<span class="glyphicon glyphicon-plus" aria-hidden="true">
								</span>&nbsp;Добавить книгу
							</a>
						</li>
						<li class="">
							{% if user.is_authenticated %}
								<a href="{% url 'loginsys:logout_user' %}">
									<span class="glyphicon glyphicon-off" aria-hidden="true">
									</span>&nbsp;Выход ({{ user }})
								</a>
							{% else %}
								<a href="{% url 'loginsys:login_user' %}">
									<span class="glyphicon glyphicon-off" aria-hidden="true">
									</span>&nbsp;Авторизация
								</a>
							{% endif %}
						</li>
					</ul>
				</div>
			</div>
		</div>
	</nav>
	{% block body %}
	{% endblock %}
	
</body>

<style>
	.navbar-brand {
    float: left;
    height: 49px;
    padding: 15px 15px;
    font-size: 30px;
    line-height: 20px;
	}
	body {
		font-family: "PT Sans";
	font-size: 20px;
	font-style: normal;
	font-variant: small-caps;
	font-weight: 700;
	line-height: 27.5px;
	}
</html>

books/templates/books/books.html
{% extends 'books/base.html' %}
{% block user %}{{ user }}{% endblock %}

{% block body %}
<div class=" books layout-form">
	<div class="layout-positioner">
		{% for book in books %}
			<a href="{% url 'books:description' book.author.id book.id %}">
				<div class="form">
					
					
					<h2 class="book-title">{{ book.title }}</h2><br>
					<div class="book-cover">
						<img src="{{ book.cover.url }}" class="book-image" class="cover">
					</div>
					<h4 class="book-year">{{ book.year }}</h4>

					
				</div>

			</a>
			{% if forloop.counter == 3 %}
				<div class="line-break">
				</div>
			{% endif %}
		{% endfor %}
	</div>
</div>
{% endblock %}

books/templates/books/description.html
{% extends 'books/base.html' %}
{% block user %}{{ user }}{% endblock %}

{% block body %}


<form action="{% url 'books:add_comment' book.author.id book.id%}" method="post">
	{% csrf_token %}
	

	<article class="description">
		<div class="positioner">
			<div class="book-title">
				<h2>{{ book.title }}</h2>
				<hr class="hr--small">
			</div>
			<div class="book-cover">
				<img src="{{ book.cover.url }}" class="book-image" class="cover">
			</div>
			<div class="description-text">
				<h4 class="book-year">{{ book.year }}</h4>
				<hr class="hr--small">
				<p>{{ book.description }}</p>
			</div>
		</div>
	</article>

	<!-- Show form -->
	<div class="form">
	{% if error_message %}
		<p>{{ error_message }}</p>
	{% else %}
		{% include 'books/form_template.html' %}
		<input type="submit" name="field" value="Отправить">
	{% endif %}
	</div>
	<!-- Show comments -->
	<section>
		<div class="comments">
			<h4>Комментарии:</h4>
			{% for comment in comments %}
				<p><strong>{{ comment.user_name }}: </strong>{{ comment.comment_text }}</p>
			{% endfor %}
		</div>
	</section>
</form>
{% endblock %}

books/templates/books/detail.html
{% extends 'books/base.html' %}
{% block user %}{{ user }}{% endblock %}

{% block body %}
<div class="layout-form">
	<div class="form">
		<h3>{{ author.writer }}</h3>
		{% if books %}
			<ul>
				{% for book in books %}
					<li>
						<a href="{% url 'books:description' book.author.id book.id %}">{{ book.title }} ({{ book.year }})</a>
					</li>
				{% endfor %}
			</ul>
		{% else %}
			<p>Тут нет книг.</p>
		{% endif %}
		<br>
		<a href="{% url 'books:add_books' %}"></a>
	</div>
</div>
{% endblock %}

books/templates/books/form_template.html
{% for field in form %}
	<div class="form-group1">
		<div class=""> <!-- col-sm-offset-21 col-sm-101 -->
			<span class="text-danger small">{{ field.errors }}</span>								
		</div>
		<label class="control-label"><h4>{{ field.label_tag }}<h4></label> <!-- control-label col-sm-2 -->
		<div class="field">{{ field }}</div> <!-- col-sm-10 -->
	</div>
{% endfor %}

books/templates/books/index.html
{% extends 'books/base.html' %}
{% block user %}{{ user }}{% endblock %}

{% block body %}
<div class="layout-form">
	<div class="form">
		<h3>Авторы:</h3>

		{% if author %}
			<ul>
				{% for person in author %}
					<li><a href="{% url 'books:detail' person.id %}">{{ person.writer }}</a></li>
				{% endfor %}
			</ul>
			
		{% else %}
			<p>Ты не можешь добавить автора</p>
		{% endif %}
	</div>
</div>
{% endblock %}

books/templates/books/search.html
{% extends 'books/base.html' %}
{% block user %}{{ user }}{% endblock %}

{% block body %}


<div class="layout-form">
	<div class="form">
		{% if error %}
			{{ error_message }}
		{% endif %}

		<h2>Результаты поиска:</h2>
		<ul>
			{% for book in books %}
				<li><a href="{% url 'books:description' book.author.id book.id %}">{{ book.author }}. {{ book.title }} ({{ book.year}})</a></li>
			{% endfor %}
		</ul>
	</div>
</div>
{% endblock %}